yarnPath: .yarn/releases/yarn-rc.js
packageExtensions:
    "@vue/cli-service@*":
        peerDependencies:
            "@vue/cli-plugin-babel": "*"
            "@vue/cli-plugin-eslint": "*"
            "@vue/cli-plugin-typescript": "*"
    "@vue/cli-plugin-typescript@*":
        peerDependencies:
            "babel-loader": "*"
    "fork-ts-checker-webpack-plugin@*":
        dependencies:
            "vue-template-compiler": "*"
        peerDependencies:
            "typescript": "*"
    "vue-loader@*":
        peerDependencies:
            "vue-template-compiler": "*"
    "vue-eslint-parser@*":
        dependencies:
            "@typescript-eslint/parser": "*"
    "vue-router@*":
        dependencies:
            "vue": "*"
    "vuex@*":
        dependencies:
            "vue": "*"
